### ISSUE TITLE
Page build failed - Hydeout not currently supported

### ISSUE THREAD

**Issue by theholy7** [fongandrew/hydeout#46]
I was running jekyll locally with with docker, and was able to use the hydeout layout. However the new layout fails to build on Github.

```
The page build failed for the `master` branch with the following error:

The hydeout theme is not currently supported on GitHub Pages. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

My current `_config.yml` file is:
```
remote_theme: fongandrew/hydeout

# Setup
title: 'Jose Antunes'
tagline: 'Code, Food, Travel'
description: 'Everyday learning and sharing'
url: https://joseantunes.tech
baseurl: ''
  # the optional subpath of your site, e.g. "/blog"
  # NB: This applies to all pages in your Jekyll site.
  # If you want to move just the blog index pages but keep
  # other pages at root, see the paginate_path and
  # sidebar_blog_link below.

author:
  name: 'Jose Antunes'
  url: https://linkedin.com/in/antunesjose

paginate: 5

github:
  repo: https://github.com/theholy7
```

and my `Gemfile` is:

```
source 'https://rubygems.org'
gem "github-pages", group: :jekyll_plugins
gem "jekyll-theme-hydeout", "~> 3.4"
```

I don't know where to search, as I think I have done things correctly. If you could help me, I'd be very thankful.

Best,
Jose
